### PR TITLE
C3JS 0.4.10

### PR DESCRIPTION
**Pull request by jdillworth**
c3.js 0.4.8 had an issue with scrolling on mobile (https://github.com/masayuki0812/c3/issues/215). Updating to latest version.

### CODE REVIEW

**Comment by aendra-rininsland** [comment]
:+1: 0.4.10 has a whole raft of stability improvements as well.

**Comment by peernohell** [comment]
Thanks :)

**Comment by aendra-rininsland** [comment]
@peernohell No, thank you! Nice implementation! :+1: :shipit:

**Comment by 0o-de-lally** [comment]
@jdillworth Thanks!

**Comment by 0o-de-lally** [comment]
@peernohell Can you please release this on atmosphere?

**Comment by peernohell** [comment]
@keyscores thanks for the reminder. I total forgot to do it :/
done

**Comment by iamnathadian** [comment]
@peernohell Can this version be put on NuGet?

**Comment by peernohell** [comment]
I don't know NuGet. But after looking on there website I'm not sure that this package have to be on it. It's a package for Meteor. Maybe you may want the classic c3 package (https://github.com/masayuki0812/c3)

**Comment by iamnathadian** [comment]
I see. It looks like I was mixed up. I was searching for a fix for mobile scrolling in C3 and my search lead me here. Thanks!

**Comment by aendra-rininsland** [comment]
@iamnathadian Lulz, totally forgot C3 was on NuGet. I have the ability to update that IIRC; will do that now. 

Why does anyone use NuGet? I've been trying to figure that out ever since masayuki0812/c3#826...

**Pull request merged**
